apiVersion: v1
kind: Service
metadata:
  name: maha-backend
  namespace: maha
spec:
  selector:
    app: maha-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: maha-frontend
  namespace: maha
spec:
  selector:
    app: maha-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: maha-redis
  namespace: maha
spec:
  selector:
    app: maha-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP