/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HudRouteImport } from './routes/hud'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowsSplatRouteImport } from './routes/api/workflows/$'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsSplatRoute = ApiWorkflowsSplatRouteImport.update({
  id: '/api/workflows/$',
  path: '/api/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/workflows/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/workflows/$'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/workflows/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  HudRoute: typeof HudRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  VoiceRoute: typeof VoiceRoute
  ApiWorkflowsSplatRoute: typeof ApiWorkflowsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$': {
      id: '/api/workflows/$'
      path: '/api/workflows/$'
      fullPath: '/api/workflows/$'
      preLoaderRoute: typeof ApiWorkflowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  HudRoute: HudRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  VoiceRoute: VoiceRoute,
  ApiWorkflowsSplatRoute: ApiWorkflowsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
