/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MahaRouteImport } from './routes/maha'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HudRouteImport } from './routes/hud'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlannerTestRouteImport } from './routes/api/planner-test'
import { Route as ApiWorkflowsOpenapiDotjsonRouteImport } from './routes/api/workflows/openapi[.]json'
import { Route as ApiWorkflowsDocsRouteImport } from './routes/api/workflows/docs'
import { Route as ApiWorkflowsSplatRouteImport } from './routes/api/workflows/$'
import { Route as ApiVoiceSplatRouteImport } from './routes/api/voice/$'
import { Route as ApiVisionSplatRouteImport } from './routes/api/vision/$'
import { Route as ApiPoliciesSplatRouteImport } from './routes/api/policies/$'
import { Route as ApiManagerSplatRouteImport } from './routes/api/manager/$'
import { Route as ApiGoalsSplatRouteImport } from './routes/api/goals/$'
import { Route as ApiDepartmentsSplatRouteImport } from './routes/api/departments/$'
import { Route as ApiBudgetSplatRouteImport } from './routes/api/budget/$'
import { Route as ApiApprovalsSplatRouteImport } from './routes/api/approvals/$'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MahaRoute = MahaRouteImport.update({
  id: '/maha',
  path: '/maha',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlannerTestRoute = ApiPlannerTestRouteImport.update({
  id: '/api/planner-test',
  path: '/api/planner-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsOpenapiDotjsonRoute =
  ApiWorkflowsOpenapiDotjsonRouteImport.update({
    id: '/api/workflows/openapi.json',
    path: '/api/workflows/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsDocsRoute = ApiWorkflowsDocsRouteImport.update({
  id: '/api/workflows/docs',
  path: '/api/workflows/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsSplatRoute = ApiWorkflowsSplatRouteImport.update({
  id: '/api/workflows/$',
  path: '/api/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSplatRoute = ApiVoiceSplatRouteImport.update({
  id: '/api/voice/$',
  path: '/api/voice/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionSplatRoute = ApiVisionSplatRouteImport.update({
  id: '/api/vision/$',
  path: '/api/vision/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoliciesSplatRoute = ApiPoliciesSplatRouteImport.update({
  id: '/api/policies/$',
  path: '/api/policies/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerSplatRoute = ApiManagerSplatRouteImport.update({
  id: '/api/manager/$',
  path: '/api/manager/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsSplatRoute = ApiGoalsSplatRouteImport.update({
  id: '/api/goals/$',
  path: '/api/goals/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsSplatRoute = ApiDepartmentsSplatRouteImport.update({
  id: '/api/departments/$',
  path: '/api/departments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetSplatRoute = ApiBudgetSplatRouteImport.update({
  id: '/api/budget/$',
  path: '/api/budget/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApprovalsSplatRoute = ApiApprovalsSplatRouteImport.update({
  id: '/api/approvals/$',
  path: '/api/approvals/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/maha': typeof MahaRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/planner-test': typeof ApiPlannerTestRoute
  '/api/approvals/$': typeof ApiApprovalsSplatRoute
  '/api/budget/$': typeof ApiBudgetSplatRoute
  '/api/departments/$': typeof ApiDepartmentsSplatRoute
  '/api/goals/$': typeof ApiGoalsSplatRoute
  '/api/manager/$': typeof ApiManagerSplatRoute
  '/api/policies/$': typeof ApiPoliciesSplatRoute
  '/api/vision/$': typeof ApiVisionSplatRoute
  '/api/voice/$': typeof ApiVoiceSplatRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/api/workflows/docs': typeof ApiWorkflowsDocsRoute
  '/api/workflows/openapi.json': typeof ApiWorkflowsOpenapiDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/maha': typeof MahaRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/planner-test': typeof ApiPlannerTestRoute
  '/api/approvals/$': typeof ApiApprovalsSplatRoute
  '/api/budget/$': typeof ApiBudgetSplatRoute
  '/api/departments/$': typeof ApiDepartmentsSplatRoute
  '/api/goals/$': typeof ApiGoalsSplatRoute
  '/api/manager/$': typeof ApiManagerSplatRoute
  '/api/policies/$': typeof ApiPoliciesSplatRoute
  '/api/vision/$': typeof ApiVisionSplatRoute
  '/api/voice/$': typeof ApiVoiceSplatRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/api/workflows/docs': typeof ApiWorkflowsDocsRoute
  '/api/workflows/openapi.json': typeof ApiWorkflowsOpenapiDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/hud': typeof HudRoute
  '/logs': typeof LogsRoute
  '/maha': typeof MahaRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/voice': typeof VoiceRoute
  '/api/planner-test': typeof ApiPlannerTestRoute
  '/api/approvals/$': typeof ApiApprovalsSplatRoute
  '/api/budget/$': typeof ApiBudgetSplatRoute
  '/api/departments/$': typeof ApiDepartmentsSplatRoute
  '/api/goals/$': typeof ApiGoalsSplatRoute
  '/api/manager/$': typeof ApiManagerSplatRoute
  '/api/policies/$': typeof ApiPoliciesSplatRoute
  '/api/vision/$': typeof ApiVisionSplatRoute
  '/api/voice/$': typeof ApiVoiceSplatRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/api/workflows/docs': typeof ApiWorkflowsDocsRoute
  '/api/workflows/openapi.json': typeof ApiWorkflowsOpenapiDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/maha'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/planner-test'
    | '/api/approvals/$'
    | '/api/budget/$'
    | '/api/departments/$'
    | '/api/goals/$'
    | '/api/manager/$'
    | '/api/policies/$'
    | '/api/vision/$'
    | '/api/voice/$'
    | '/api/workflows/$'
    | '/api/workflows/docs'
    | '/api/workflows/openapi.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/maha'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/planner-test'
    | '/api/approvals/$'
    | '/api/budget/$'
    | '/api/departments/$'
    | '/api/goals/$'
    | '/api/manager/$'
    | '/api/policies/$'
    | '/api/vision/$'
    | '/api/voice/$'
    | '/api/workflows/$'
    | '/api/workflows/docs'
    | '/api/workflows/openapi.json'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/chat'
    | '/dashboard'
    | '/hud'
    | '/logs'
    | '/maha'
    | '/settings'
    | '/tools'
    | '/voice'
    | '/api/planner-test'
    | '/api/approvals/$'
    | '/api/budget/$'
    | '/api/departments/$'
    | '/api/goals/$'
    | '/api/manager/$'
    | '/api/policies/$'
    | '/api/vision/$'
    | '/api/voice/$'
    | '/api/workflows/$'
    | '/api/workflows/docs'
    | '/api/workflows/openapi.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  HudRoute: typeof HudRoute
  LogsRoute: typeof LogsRoute
  MahaRoute: typeof MahaRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  VoiceRoute: typeof VoiceRoute
  ApiPlannerTestRoute: typeof ApiPlannerTestRoute
  ApiApprovalsSplatRoute: typeof ApiApprovalsSplatRoute
  ApiBudgetSplatRoute: typeof ApiBudgetSplatRoute
  ApiDepartmentsSplatRoute: typeof ApiDepartmentsSplatRoute
  ApiGoalsSplatRoute: typeof ApiGoalsSplatRoute
  ApiManagerSplatRoute: typeof ApiManagerSplatRoute
  ApiPoliciesSplatRoute: typeof ApiPoliciesSplatRoute
  ApiVisionSplatRoute: typeof ApiVisionSplatRoute
  ApiVoiceSplatRoute: typeof ApiVoiceSplatRoute
  ApiWorkflowsSplatRoute: typeof ApiWorkflowsSplatRoute
  ApiWorkflowsDocsRoute: typeof ApiWorkflowsDocsRoute
  ApiWorkflowsOpenapiDotjsonRoute: typeof ApiWorkflowsOpenapiDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maha': {
      id: '/maha'
      path: '/maha'
      fullPath: '/maha'
      preLoaderRoute: typeof MahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hud': {
      id: '/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planner-test': {
      id: '/api/planner-test'
      path: '/api/planner-test'
      fullPath: '/api/planner-test'
      preLoaderRoute: typeof ApiPlannerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/openapi.json': {
      id: '/api/workflows/openapi.json'
      path: '/api/workflows/openapi.json'
      fullPath: '/api/workflows/openapi.json'
      preLoaderRoute: typeof ApiWorkflowsOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/docs': {
      id: '/api/workflows/docs'
      path: '/api/workflows/docs'
      fullPath: '/api/workflows/docs'
      preLoaderRoute: typeof ApiWorkflowsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$': {
      id: '/api/workflows/$'
      path: '/api/workflows/$'
      fullPath: '/api/workflows/$'
      preLoaderRoute: typeof ApiWorkflowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/$': {
      id: '/api/voice/$'
      path: '/api/voice/$'
      fullPath: '/api/voice/$'
      preLoaderRoute: typeof ApiVoiceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/$': {
      id: '/api/vision/$'
      path: '/api/vision/$'
      fullPath: '/api/vision/$'
      preLoaderRoute: typeof ApiVisionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policies/$': {
      id: '/api/policies/$'
      path: '/api/policies/$'
      fullPath: '/api/policies/$'
      preLoaderRoute: typeof ApiPoliciesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/$': {
      id: '/api/manager/$'
      path: '/api/manager/$'
      fullPath: '/api/manager/$'
      preLoaderRoute: typeof ApiManagerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals/$': {
      id: '/api/goals/$'
      path: '/api/goals/$'
      fullPath: '/api/goals/$'
      preLoaderRoute: typeof ApiGoalsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/$': {
      id: '/api/departments/$'
      path: '/api/departments/$'
      fullPath: '/api/departments/$'
      preLoaderRoute: typeof ApiDepartmentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budget/$': {
      id: '/api/budget/$'
      path: '/api/budget/$'
      fullPath: '/api/budget/$'
      preLoaderRoute: typeof ApiBudgetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals/$': {
      id: '/api/approvals/$'
      path: '/api/approvals/$'
      fullPath: '/api/approvals/$'
      preLoaderRoute: typeof ApiApprovalsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  HudRoute: HudRoute,
  LogsRoute: LogsRoute,
  MahaRoute: MahaRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  VoiceRoute: VoiceRoute,
  ApiPlannerTestRoute: ApiPlannerTestRoute,
  ApiApprovalsSplatRoute: ApiApprovalsSplatRoute,
  ApiBudgetSplatRoute: ApiBudgetSplatRoute,
  ApiDepartmentsSplatRoute: ApiDepartmentsSplatRoute,
  ApiGoalsSplatRoute: ApiGoalsSplatRoute,
  ApiManagerSplatRoute: ApiManagerSplatRoute,
  ApiPoliciesSplatRoute: ApiPoliciesSplatRoute,
  ApiVisionSplatRoute: ApiVisionSplatRoute,
  ApiVoiceSplatRoute: ApiVoiceSplatRoute,
  ApiWorkflowsSplatRoute: ApiWorkflowsSplatRoute,
  ApiWorkflowsDocsRoute: ApiWorkflowsDocsRoute,
  ApiWorkflowsOpenapiDotjsonRoute: ApiWorkflowsOpenapiDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
